/* EDITORIAL — descriptive enrichment never participates in daily selection. */
const EDITORIAL_EDITS={
 jfk:{context:'El 22 de noviembre de 1963, Kennedy recorría Dallas en una caravana presidencial cuando recibió los disparos. Fue trasladado al hospital Parkland, donde se confirmó su muerte. Horas después, Lyndon B. Johnson juró como presidente a bordo del Air Force One, antes de regresar a Washington.',significance:'La visita a Texas buscaba fortalecer sus apoyos políticos de cara a las elecciones del año siguiente. El asesinato convirtió ese viaje electoral en una sucesión presidencial de emergencia.',fact:'Preguntamos por el asesinato de Kennedy en Dallas: 22 de noviembre de 1963.',sourceLabel:'John F. Kennedy Presidential Library',source:'https://www.jfklibrary.org/learn/about-jfk/jfk-in-history/november-22-1963-death-of-the-president'},
 apollo11:{context:'En julio de 1969, Neil Armstrong y Buzz Aldrin descendieron a la superficie lunar mientras Michael Collins permanecía en órbita. Apollo 11 había despegado el 16 de julio y alunizó el día 20. Fue la primera vez que seres humanos llegaron a otro mundo.',significance:'La misión utilizó el módulo lunar para descender y el módulo de mando para regresar a la Tierra.',sourceLabel:'NASA · Apollo 11',source:'https://www.nasa.gov/missions/apollo/apollo-11/apollo-11-mission-overview/'},
 walkman:{prompt:'¿En qué año comenzó a venderse el primer Walkman en Japón?',context:'El primer Walkman llegó a Japón en 1979. El modelo TPS-L2 permitía escuchar casetes con auriculares mientras uno caminaba o viajaba. Tenía dos conexiones para auriculares y un botón para hablar con el acompañante sin quitarse los cascos.',significance:'Ayudó a convertir la música grabada en una experiencia portátil y personal.',sourceLabel:'MoMA · Sony Walkman',source:'https://www.moma.org/collection/works/185344'},
 ibmpc:{context:'IBM presentó el Personal Computer 5150 en agosto de 1981. Su llegada dio un nuevo peso a los ordenadores personales en empresas y hogares. La arquitectura del equipo abrió espacio a fabricantes de componentes, programas y equipos compatibles.',significance:'El término «PC» acabaría identificándose con una familia de ordenadores compatibles, más allá de la marca IBM.',sourceLabel:'IBM · The IBM PC',source:'https://www.ibm.com/history/personal-computer'},
 ipod:{context:'Apple presentó el iPod el 23 de octubre de 2001. El modelo original tenía un disco de 5 GB y prometía llevar unas mil canciones en el bolsillo. Se sincronizaba con iTunes en un Mac mediante una conexión FireWire.',significance:'Su propuesta combinaba el reproductor con una biblioteca de música organizada en el ordenador.',sourceLabel:'Apple · Presentación del iPod',source:'https://www.apple.com/newsroom/2001/10/23Apple-Presents-iPod/'},
 iphone:{prompt:'¿En qué año comenzó a venderse el primer iPhone en Estados Unidos?',context:'El primer iPhone salió a la venta en Estados Unidos el 29 de junio de 2007, después de su presentación en enero. Reunía teléfono, reproductor de música y acceso a Internet en un dispositivo controlado principalmente desde una pantalla táctil.',significance:'Preguntamos por el comienzo de las ventas estadounidenses, no por su llegada posterior a cada país.',sourceLabel:'Apple · Inicio de ventas del iPhone',source:'https://www.apple.com/newsroom/2007/06/28iPhone-Premieres-This-Friday-Night-at-Apple-Retail-Stores/'},
 web:{title:'La Web se abre al público',prompt:'¿En qué año Tim Berners-Lee anunció públicamente la Web en Internet?',context:'En agosto de 1991, Tim Berners-Lee anunció el proyecto World Wide Web en Internet. La propuesta conectaba documentos mediante enlaces y permitía consultarlos con un navegador. Internet ya existía: la Web era una nueva manera de publicar y recorrer información sobre esa red.',fact:'Preguntamos por el anuncio público en Internet de agosto de 1991, no por el primer servidor, operativo en 1990.',significance:'Internet es la red de comunicaciones; la Web es uno de sus servicios.',sourceLabel:'CERN · Historia de la Web',source:'https://home.cern/science/computing/the-birth-of-the-web/short-history-web/'},
 wwwproposal:{context:'En 1989, Tim Berners-Lee presentó en el CERN una propuesta para compartir información mediante documentos enlazados. Buscaba facilitar el trabajo entre investigadores. La idea se convirtió después en la World Wide Web, con servidores, páginas y navegadores.',significance:'Esta pregunta se refiere a la propuesta inicial; el anuncio público en Internet llegó dos años después.',sourceLabel:'CERN · Historia de la Web',source:'https://home.cern/science/computing/the-birth-of-the-web/short-history-web/'},
 dolly:{context:'Dolly nació el 5 de julio de 1996, aunque su existencia se anunció al mundo en febrero de 1997. Fue el primer mamífero clonado a partir de una célula adulta. El núcleo procedía de una célula de la glándula mamaria de otra oveja.',significance:'Mostró que una célula adulta especializada conservaba la información genética necesaria para desarrollar un organismo completo.',fact:'Preguntamos por el nacimiento de Dolly en 1996, no por el anuncio público de 1997.',sourceLabel:'National Museums Scotland · Dolly',source:'https://www.nms.ac.uk/discover-catalogue/the-story-of-dolly-the-sheep'},
 hubble:{context:'El telescopio espacial Hubble fue lanzado el 24 de abril de 1990 a bordo del transbordador Discovery. Observar desde la órbita terrestre permitía superar buena parte de las limitaciones que impone la atmósfera a los telescopios en tierra.',significance:'La fotografía muestra el telescopio en órbita, no el momento del despegue.',sourceLabel:'NASA · Historia del Hubble',source:'https://science.nasa.gov/mission/hubble/overview/the-history-of-hubble/'},
 curiosity:{context:'Curiosity llegó al cráter Gale de Marte en agosto de 2012. Su sistema de aterrizaje lo bajó con cables desde una plataforma propulsada: la llamada «grúa aérea». Ya en la superficie, el rover comenzó a estudiar rocas, suelo y atmósfera.',significance:'La misión investigaba si Marte había tenido condiciones favorables para la vida. La fotografía es un autorretrato posterior, tomado en Windjana.',sourceLabel:'NASA JPL · Mars Science Laboratory',source:'https://www.jpl.nasa.gov/missions/mars-science-laboratory-curiosity-rover-msl/'},
 sputnik:{context:'La Unión Soviética lanzó Sputnik 1 el 4 de octubre de 1957. Era una esfera metálica con cuatro antenas y una masa de unos 83 kilogramos. Se convirtió en el primer satélite artificial en órbita terrestre, desde donde transmitía señales de radio.',significance:'El lanzamiento marcó el comienzo de la era espacial y aceleró la competencia tecnológica entre las grandes potencias.',sourceLabel:'NASA · Sputnik',source:'https://www.nasa.gov/history/sputnik/sputorig.html'},
 playstation:{context:'La primera PlayStation se lanzó en Japón en 1994. Sony apostó por los discos CD-ROM y los gráficos tridimensionales. El mayor espacio del disco frente a muchos cartuchos facilitaba incorporar más audio, vídeo y contenido a los juegos.',significance:'Preguntamos por Japón: los lanzamientos norteamericano y europeo llegaron en 1995.',sourceLabel:'PlayStation · Historia de la consola original',source:'https://www.playstation.com/en-us/playstation-history/1994-ps-one/'},
 gameboy:{prompt:'¿En qué año se lanzó la Game Boy original en Japón?',context:'La Game Boy se lanzó en Japón en 1989. Su pantalla monocroma y sus cartuchos intercambiables permitían llevar los juegos fuera del salón. Tetris se convirtió en uno de los títulos más reconocibles de esta consola portátil.',significance:'La fecha corresponde al lanzamiento japonés de la consola original, no a sus revisiones.',sourceLabel:'Nintendo · Game Boy',source:'https://www.nintendo.com/en-gb/Hardware/Nintendo-History/Game-Boy/Game-Boy-627031.html'},
 higgs:{prompt:'¿En qué año ATLAS y CMS anunciaron una nueva partícula compatible con el bosón de Higgs?',context:'El 4 de julio de 2012, los experimentos ATLAS y CMS del CERN anunciaron una nueva partícula compatible con el bosón de Higgs. Los análisis posteriores permitieron estudiar sus propiedades y confirmar su identificación.',significance:'Aportó evidencia clave sobre el mecanismo asociado al origen de la masa de las partículas elementales.',sourceLabel:'CERN · El bosón de Higgs',source:'https://home.cern/science/physics/higgs-boson/'},
 sgtpepper:{context:'The Beatles publicaron Sgt. Pepper’s Lonely Hearts Club Band en 1967. Su octavo álbum de estudio presentaba a la banda bajo una identidad ficticia y quedó asociado al llamado Verano del Amor.',significance:'El título completo pertenece a un disco de The Beatles, no a una banda distinta.',sourceLabel:'The Beatles · Sgt. Pepper',source:'https://www.thebeatles.com/sgt-peppers-lonely-hearts-club-band-0'},
 plebiscito88:{context:'El 5 de octubre de 1988, Chile votó si Augusto Pinochet debía continuar en la presidencia. La opción No obtuvo aproximadamente el 54 % y abrió el camino a las elecciones presidenciales y parlamentarias de 1989.',significance:'La votación fue un paso decisivo de la transición; el cambio de gobierno se produjo en 1990.',sourceLabel:'Biblioteca del Congreso Nacional de Chile',source:'https://www.bcn.cl/historiapolitica/hitos_periodo/detalle_periodo.html?per=1973-1990'},
 constitution1980:{title:'Plebiscito constitucional bajo Pinochet',prompt:'¿En qué año se votó el texto constitucional elaborado durante la dictadura de Pinochet?',context:'El plebiscito se celebró el 11 de septiembre de 1980, bajo la dictadura y sin registros electorales vigentes. La Constitución entró en vigor en marzo de 1981: la consulta y su entrada en vigencia ocurrieron en años distintos.',fact:'Preguntamos por el plebiscito de septiembre de 1980.',sourceLabel:'Biblioteca del Congreso Nacional de Chile',source:'https://www.bcn.cl/historiapolitica/hitos_periodo/detalle_periodo.html?per=1973-1990'},
 golpe1973:{context:'El golpe de Estado del 11 de septiembre de 1973 derrocó al gobierno de Salvador Allende. La Junta Militar asumió el poder y el Congreso fue disuelto ese mismo mes. Comenzó así una dictadura que se prolongó hasta 1990.',sourceLabel:'Biblioteca del Congreso Nacional de Chile',source:'https://www.bcn.cl/historiapolitica/hitos_periodo/detalle_periodo.html?per=1973-1990'},
 win95:{title:'Windows y el menú Inicio',prompt:'¿En qué año salió la versión de Windows que estrenó el menú Inicio?'}
};
const CONTEXT_ONLY_IMAGES=new Set(['web','google','bitcoin','sgtpepper','nevermind','kida','plebiscito88','heart_transplant','nobelneruda','rios1998','estallido2019','mtv','dragonball','friends','zelda','curiosity']);
const ARCHIVE_IMAGES={
 apollo11:{image:'assets/apollo11.jpg',imageAlt:'Buzz Aldrin sobre la superficie lunar, fotografiado durante Apollo 11',imageCredit:'NASA / Neil Armstrong · AS11-40-5903',imageSource:'https://images.nasa.gov/details/as11-40-5903'},
 hubble:{image:'assets/hubble.webp',imageAlt:'El telescopio Hubble en órbita sobre la Tierra',imageCredit:'NASA · Telescopio Hubble en órbita',imageSource:'https://science.nasa.gov/mission/hubble/overview/the-history-of-hubble/'},
 curiosity:{image:'assets/curiosity.jpg',imageAlt:'Autorretrato de Curiosity en Windjana, Marte; imagen posterior al aterrizaje',imageCredit:'NASA / JPL-Caltech / MSSS · Windjana, 2014',imageSource:'https://science.nasa.gov/mission/msl-curiosity/'}
};
const IMAGE_DESCRIPTIONS={walkman:'Reproductor de casetes con auriculares',ibmpc:'Ordenador beige con teclado y monitor',web:'Globo terráqueo con conexiones',google:'Lupa sobre una red de conexiones',ipod:'Reproductor de música con rueda circular',iphone:'Teléfono de pantalla táctil',bitcoin:'Moneda dorada con circuitos',berlinwall:'Apertura en un muro con grafitis y personas celebrando',dolly:'Retrato de una oveja blanca',jaws:'Aleta de tiburón en el mar',alien:'Huevo de criatura extraterrestre',bttf:'Automóvil con luces y estelas de fuego',jurassic:'Silueta de dinosaurio tras una valla',titanic:'Transatlántico iluminado de noche',matrix:'Columnas de símbolos luminosos',spirited:'Personaje enmascarado sobre un puente',sgtpepper:'Banda tocando sobre un escenario',darkside:'Prisma que separa la luz en colores',nevermind:'Guitarra eléctrica',kida:'Montañas junto a un lago',gameboy:'Consola portátil con pantalla monocroma',minecraft:'Paisaje cúbico con árboles y agua',plebiscito88:'Urna con bandera chilena',mineros:'Cápsula de rescate y trabajadores',rubik:'Cubo de caras multicolores',dna:'Modelo de doble hélice',sputnik:'Satélite esférico con antenas',heart_transplant:'Equipo médico en un quirófano',cubancrisis:'Buques frente a una costa',mandela:'Persona saliendo por unas puertas abiertas',tetris:'Bloques de colores encajados',supermario:'Botas y seta roja de un videojuego',valdivia1960:'Gran ola junto a una ciudad costera',nobelneruda:'Libro con medallón dorado',rios1998:'Raqueta y pelota de tenis',estallido2019:'Pasajeros y tren en una estación de metro',cd1982:'Disco compacto iridiscente',mtv:'Equipo de televisión filmando una actuación',barbie:'Silueta rosa de una muñeca',dragonball:'Viñetas de manga',friends:'Sofá con tazas de café',zelda:'Espada y escudo de fantasía'};
for(const q of QUESTIONS){
  q.imageType='illustration';q.imageRole=CONTEXT_ONLY_IMAGES.has(q.id)?'context':'support';q.editorialVerified=Boolean(EDITORIAL_EDITS[q.id]?.source);
  if(EDITORIAL_EDITS[q.id])Object.assign(q,EDITORIAL_EDITS[q.id]);
  if(q.image)q.imageAlt='Ilustración de apoyo: '+(IMAGE_DESCRIPTIONS[q.id]||q.title)+'.';
  if(ARCHIVE_IMAGES[q.id])Object.assign(q,ARCHIVE_IMAGES[q.id],{imageType:'documentary'});
  if(['mac','starwars','playstation'].includes(q.id)){q.image='';q.imageAlt='';q.imageCredit='';q.imageSource='';}
}
