/* GAME ENGINE, TIMELINE AND SHARING */
let currentView='hoy',round=null,lastSummary=null,timelineSelection=null;
let audioContext=null,toastTimer=null;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200)}
function tone(kind='confirm'){
  const p=getState().preferences;if(!p.sound||p.volume<=0)return;
  try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext=audioContext||new Audio();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});const notes={confirm:[440],exact:[660,880],finish:[440,554,660],achievement:[523,659,784,1047],place:[330]}[kind]||[440],start=audioContext.currentTime;
    notes.forEach((f,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),t=start+i*.09;osc.type='sine';osc.frequency.value=f;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(p.volume*.16,t+.012);gain.gain.exponentialRampToValueAtTime(.0001,t+.15);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+.18)});
  }catch{/* Audio is optional; game remains usable. */}
}
function applyPreferences(){const s=getState(),palette=availablePalettes(s).includes(s.preferences.palette)?s.preferences.palette:'amber';document.documentElement.style.setProperty('--accent',{amber:'#f4c76d',ocean:'#7acff2',violet:'#c4b1ff'}[palette]);document.documentElement.dataset.motion=s.preferences.motion;$('soundToggle').textContent=`Sonido: ${s.preferences.sound?'sí':'no'}`;$('soundToggle').setAttribute('aria-pressed',String(s.preferences.sound));$('soundToggle').setAttribute('aria-label',s.preferences.sound?'Desactivar sonido':'Activar sonido')}
function refreshHeader(){const s=getState(),due=eligibleReviews(s).filter(x=>x.dueIn<=0).length;$('weeklyActivity').textContent=`${recentActivity(s)} de 7 días · racha ${calcStreak(s.sessions)}`;$('dueBadge').textContent=due;$('dueBadge').hidden=due===0;applyPreferences()}
function showView(name,{focus=true}={}){
  if(!['hoy','repaso','orden','coleccion','estadisticas'].includes(name))name='hoy';
  currentView=name;round=null;document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===name;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
  if(name==='hoy')renderDaily();if(name==='repaso')renderReview();if(name==='orden')renderTimeline();if(name==='coleccion')renderCollection();if(name==='estadisticas')renderStats();refreshHeader();if(focus)$('main').focus({preventScroll:true});
}
function renderDaily(){const s=getState(),done=s.sessions.find(x=>x.date===dateKey());if(done){renderSummary(done);return}if(s.activeSession){round=s.activeSession;if(round.index>=round.questionIds.length){completeRound();return}renderGame();return}renderCover()}
function renderCover(){const s=getState(),entry=dailyEntry(),n=entry.questions.filter(q=>!discoveredIds(s).has(q.id)).length;setView(`<section class="surface cover"><span class="cover-mark">EL DESAFÍO DIARIO</span><div class="stack"><span class="eyebrow">${esc(new Date().toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'}))}</span><h1>QUÉ AÑO #${challengeNumber()}</h1></div><p>Cinco hitos. Elige su año y descubre la historia detrás de cada uno.</p><div class="cover-meta"><span class="pill">2 fáciles · 2 medias · 1 difícil</span><span class="pill">${n} por descubrir</span>${entry.specialTheme?`<span class="pill cat">Especial ${esc(entry.specialTheme)}</span>`:''}</div><button class="primary" data-action="start-daily">Comenzar desafío →</button><small>${recentActivity(s)} días jugados esta semana · Racha de ${calcStreak(s.sessions)}</small></section>`)}
function createRound(mode,questions){return {uid:`${mode}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,date:dateKey(),mode,questionIds:questions.map(q=>q.id),index:0,phase:'question',guess:1990,assisted:false,answers:[],newDiscoveries:0,newAchievements:[],contentVersion:CONTENT_VERSION,scheduleVersion:SCHEDULE_VERSION}}
function persistRound(){if(!round)return;const s=getState();s[round.mode==='daily'?'activeSession':'practiceDraft']=round;setState(s)}
function startDaily(){const s=getState();if(s.sessions.some(x=>x.date===dateKey())){renderDaily();return}round=s.activeSession||createRound('daily',dailyQuestions());s.dailyIntroDate=dateKey();persistRound();renderGame();focusYear()}
function startPractice(mode='all',category='Todas',count=5,ids=null){const qs=practiceQuestions(category,mode,count,ids);if(!qs.length){toast(mode==='weakest'?'Juega al menos tres fechas de una categoría para identificar dónde practicar.':'No hay preguntas disponibles con este filtro.');return}currentView='repaso';round=createRound(mode==='due'?'review':'practice',qs);persistRound();document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view==='repaso');if(b.dataset.view==='repaso')b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});renderGame();focusYear()}
function resumePractice(){const d=getState().practiceDraft;if(!d)return;round=d;currentView='repaso';if(round.index>=round.questionIds.length){completeRound();return}renderGame();focusYear()}
function focusYear(){requestAnimationFrame(()=>{if(round?.phase==='question'&&window.matchMedia('(pointer:fine)').matches)$('yearInput')?.focus({preventScroll:true})})}
function setView(html){$('view').innerHTML=html;document.querySelectorAll('img[data-fallback]').forEach(img=>{img.addEventListener('error',()=>{const figure=img.closest('figure');if(figure)figure.remove();document.querySelector('.game-body')?.classList.add('no-media')},{once:true})})}
function answerDeltaCopy(a){
  if(a.skipped)return 'Año revelado y guardado para repasar.';
  if(a.error===0)return 'Tu respuesta fue exacta.';
  const unit=a.error===1?'año':'años';
  return a.guess<a.actual?`Te faltó ${a.error} ${unit}.`:`Te pasaste por ${a.error} ${unit}.`;
}
/* v1.8.6: implementación histórica conservada para evidencia de paridad; Atlas es el writer canónico. */
function legacyTemporalScaleV11(a){
  if(a.skipped)return `<div class="temporal-scale reveal-scale" role="img" aria-label="Fecha revelada: ${a.actual}. Queda para repaso"><div class="temporal-track"><i class="temporal-marker correct exact" style="--pos:50%"><b><small>FECHA</small><span>${a.actual}</span></b></i></div><div class="temporal-distance"><strong>Fecha revelada</strong><span>Queda para repaso</span></div></div>`;
  if(a.error===0)return `<div class="temporal-scale exact-scale" role="img" aria-label="Tu respuesta ${a.guess} coincide con el año correcto"><div class="temporal-track"><i class="temporal-marker exact" style="--pos:50%"><b><small>TU RESPUESTA · CORRECTO</small><span>${a.actual}</span></b></i></div><div class="temporal-distance"><strong>Exacta</strong><span>0 años de distancia</span></div></div>`;
  const diff=Math.abs(a.guess-a.actual),unit=diff===1?'año':'años',guessFirst=a.guess<a.actual;
  const spread=diff<=2?24:diff<=5?38:diff<=20?54:diff<=50?64:72;
  const left=50-spread/2,right=50+spread/2;
  const guessPos=(guessFirst?left:right).toFixed(1)+'%',correctPos=(guessFirst?right:left).toFixed(1)+'%';
  const cls=diff<=2?'scale-near':diff<=5?'scale-close':diff<=20?'scale-medium':diff<=50?'scale-wide':'scale-decades';
  const note=diff>20?'<small>Escala resumida para facilitar la comparación</small>':'';
  return `<div class="temporal-scale ${cls}" role="img" aria-label="Tu respuesta ${a.guess}; año correcto ${a.actual}; diferencia ${diff} ${unit}"><div class="temporal-track"><i class="temporal-marker guess" style="--pos:${guessPos}"><b><small>TU</small><span>${a.guess}</span></b></i><i class="temporal-marker correct" style="--pos:${correctPos}"><b><small>CORRECTO</small><span>${a.actual}</span></b></i></div><div class="temporal-distance"><strong>${diff} ${unit} de distancia</strong><span>${a.guess<a.actual?'Tu estimación quedó antes':'Tu estimación quedó después'}</span>${note}</div></div>`;
}

function legacyRenderGameV11(){
  if(!round)return;const q=displayQuestion(round.questionIds[round.index]);if(!q){toast('No se pudo recuperar esta pregunta.');return}
  document.documentElement.style.setProperty('--cat',CATEGORY_COLORS[q.category]||'#7acff2');
  const answered=round.phase==='answer',a=round.answers[round.index],image=safeAsset(q.image),showImage=image&&(q.imageRole!=='context'||answered),daily=round.mode==='daily',label=daily?`#${challengeNumber(parseDateKey(round.date))}`:round.mode==='review'?'Repaso':'Práctica';
  const questionFig=!answered&&showImage?`<figure class="art-panel"><img src="${image}" alt="${esc(q.imageAlt)}" data-fallback><figcaption>${q.imageType==='documentary'?'Fotografía de archivo':'Ilustración de apoyo'}</figcaption></figure>`:'';
  const feedbackFig=answered&&image?`<figure class="feedback-media"><img src="${image}" alt="${esc(q.imageAlt)}" data-fallback><figcaption>${q.imageType==='documentary'?'Fotografía de archivo':'Ilustración de apoyo'}</figcaption></figure>`:'';
  const roundLabel=`Pregunta ${round.index+1} de ${round.questionIds.length}`;
  const header=`<header class="game-header"><div class="game-meta"><div class="row"><span class="pill cat">${esc(q.category)}</span><span class="pill">${DIFFICULTY_LABELS[q.difficulty]}</span></div><span class="round-label">${roundLabel}</span></div><div class="counter">${label}${daily&&round.date!==dateKey()?`<br>${round.date}`:''}</div><ol class="round-progress" style="--rounds:${round.questionIds.length}" aria-label="${roundLabel}">${round.questionIds.map((_,i)=>{const state=i<round.index?'done':i===round.index?'current':'pending',copy=state==='done'?`Ronda ${i+1} completada`:state==='current'?`Ronda ${i+1} actual`:`Ronda ${i+1} pendiente`;return `<li class="${state}"><b aria-hidden="true">${state==='done'?'✓':i+1}</b><span class="sr-only">${copy}</span></li>`}).join('')}</ol></header>`;
  let content,footer;
  if(answered){
    const grade=a.skipped?'Fecha revelada':a.error===0?'Exacto':a.error<=2?'Muy cerca':a.error<=5?'Cerca':a.error<=10?'A cierta distancia':'Lejos',st=getState().questionStats[q.id],context=q.context||q.fact,delta=answerDeltaCopy(a),source=q.source&&q.sourceLabel?`<a class="source-link" href="${esc(q.source)}" target="_blank" rel="noopener noreferrer">Fuente · ${esc(q.sourceLabel)} ↗</a>`:'';
    content=`<div class="feedback-layout ${feedbackFig?'has-feedback-media':'no-feedback-media'}"><section class="feedback-result" aria-label="Resultado de la respuesta"><span class="result-tag" style="--result:${resultColor(a)}">${grade}</span><div class="answer-verdict"><div class="answer-year-block"><span>Año correcto</span><strong class="feedback-year">${a.actual}</strong></div><p class="answer-delta">${esc(delta)}</p>${!a.skipped?`<p class="answer-comparison">Tu respuesta: <strong>${a.guess}</strong><span class="score-chip">+${a.points} pts</span></p>`:`<p class="answer-comparison">0 puntos · guardada para repasar</p>`}</div>${legacyTemporalScaleV11(a)}</section><section class="feedback-context" aria-labelledby="questionTitle"><div class="feedback-context-copy"><span class="eyebrow">EN CONTEXTO</span><h1 id="questionTitle">${esc(q.title)}</h1><p class="prompt">${esc(q.prompt)}</p></div>${feedbackFig}<div class="feedback-history"><p class="context-copy">${esc(context)}</p><div class="answer-links"><button class="secondary" data-action="detail" data-id="${q.id}">Ampliar contexto</button><span class="pill ${mastery(st).key==='mastered'?'good':''}">${esc(mastery(st).label)}</span>${source}</div>${a.assisted?'<small>Respuesta con ayuda; esta fecha queda fuera de consolidación.</small>':''}</div></section></div>`;
    footer=`<span class="shortcut">Enter para continuar · ${round.mode==='daily'?'Tu progreso está guardado':'No afecta la racha diaria'}</span><button class="primary" id="primaryAction" data-action="next">${round.index===round.questionIds.length-1?'Ver resultados':'Siguiente'} →</button>`;
  }else{
    content=`<div class="question-panel question-body"><div class="question-copy"><span class="eyebrow">${esc(q.kind)}</span><h1 id="questionTitle">${esc(q.title)}</h1><p class="prompt">${esc(q.prompt)}</p></div><div class="year-control"><span class="year-control-title">Tu estimación</span><div class="year-instrument"><button class="year-step year-step-wide" data-action="adjust" data-step="-10" aria-label="Restar diez años">−10</button><button class="year-step" data-action="adjust" data-step="-1" aria-label="Restar un año">−1</button><div class="year-readout"><input id="yearInput" class="year-input" type="number" min="${GLOBAL_MIN_YEAR}" max="${GLOBAL_MAX_YEAR}" step="1" value="${round.guess}" inputmode="numeric" aria-label="Año de tu respuesta"><label for="yearInput">año</label></div><button class="year-step" data-action="adjust" data-step="1" aria-label="Sumar un año">+1</button><button class="year-step year-step-wide" data-action="adjust" data-step="10" aria-label="Sumar diez años">+10</button></div><div class="year-slider-wrap"><input id="yearSlider" type="range" min="${GLOBAL_MIN_YEAR}" max="${GLOBAL_MAX_YEAR}" step="1" value="${round.guess}" aria-label="Seleccionar año"><div class="range-ends"><span>${GLOBAL_MIN_YEAR}</span><span>Mueve para explorar</span><span>${GLOBAL_MAX_YEAR}</span></div></div>${round.assisted?`<small class="hint-copy">Ayuda: década de ${decadeOf(q.year)}.</small>`:''}</div></div>`;
    footer=`<div class="row"><button class="text-button" data-action="skip">No lo sé</button>${!daily&&!round.assisted?'<button class="text-button" data-action="hint">Ayuda</button>':''}</div><button class="primary" id="primaryAction" data-action="answer">Responder</button>`;
  }
  setView(`<section class="surface game game-v11 ${answered?'is-answered':'is-question'}" aria-labelledby="questionTitle">${header}<div class="game-body ${!answered&&!showImage?'no-media':''} ${answered?'answered':''}">${questionFig}${content}</div><footer class="game-footer">${footer}</footer></section>`);
  if(showImage&&!answered)document.querySelector('.question-panel')?.insertAdjacentHTML('beforeend','<button class="text-button compact-image" data-action="game-image">Ver imagen de apoyo</button>');
}

function setYear(value,{render=false}={}){if(!round||round.phase!=='question')return;const n=Number(value);if(!Number.isFinite(n))return;round.guess=Math.round(Math.max(GLOBAL_MIN_YEAR,Math.min(GLOBAL_MAX_YEAR,n)));persistRound();if(render)renderGame();else{if($('yearInput'))$('yearInput').value=round.guess;if($('yearSlider'))$('yearSlider').value=round.guess}}
function commitAnswer(skipped=false){
  if(!round||round.phase!=='question')return;
  const input=$('yearInput'),guess=Number(input?input.value:round.guess);if(!skipped&&(!Number.isInteger(guess)||guess<GLOBAL_MIN_YEAR||guess>GLOBAL_MAX_YEAR||input?.value==='')){toast(`Escribe un año entre ${GLOBAL_MIN_YEAR} y ${GLOBAL_MAX_YEAR}.`);input?.focus();return}
  const s=getState(),q=displayQuestion(round.questionIds[round.index]),actual=QUESTION_BY_ID.get(q.id).year,isNew=!discoveredIds(s).has(q.id),error=skipped?null:Math.abs(guess-actual);
  const a={id:q.id,title:q.title,category:q.category,actual,guess:skipped?null:guess,error,points:skipped?0:points(error),skipped,assisted:round.assisted};
  $('answerAnnouncement').textContent=`Año correcto: ${actual}. ${answerDeltaCopy({skipped,error,guess:skipped?null:guess,actual})}${skipped?'':' '+points(error)+' puntos.'}`;
  recordAnswer(s,a,dateKey());round.answers.push(a);round.phase='answer';if(isNew)round.newDiscoveries++;persistRound();renderGame();refreshHeader();tone(!skipped&&error===0?'exact':'confirm');$('primaryAction')?.focus({preventScroll:true});
}
function nextQuestion(){if(!round||round.phase!=='answer')return;round.index++;round.phase='question';round.guess=1990;round.assisted=false;persistRound();if(round.index>=round.questionIds.length)completeRound();else{renderGame();focusYear()}}
function completeRound(){
  if(!round||round.answers.length!==round.questionIds.length)return;
  const s=getState(),mode=round.mode,key=mode==='daily'?'sessions':mode==='review'?'reviewSessions':'practiceSessions';
  if(s[key].some(x=>x.uid===round.uid)||(mode==='daily'&&s.sessions.some(x=>x.date===round.date))){const existing=s[key].find(x=>x.uid===round.uid||x.date===round.date);s[mode==='daily'?'activeSession':'practiceDraft']=null;setState(s);round=null;renderSummary(existing);return}
  // Unfinished legacy rounds record memory only when not already stored.
  round.answers.forEach(a=>recordAnswer(s,a,a.date||round.date));
  const run=sessionFromAnswers(round.date,round.answers,mode,{uid:round.uid,newDiscoveries:round.newDiscoveries||0});s[key].push(run);s[key].sort((a,b)=>a.date.localeCompare(b.date));if(mode!=='daily')s[key]=s[key].slice(-300);s.bestStreak=Math.max(s.bestStreak,calcStreak(s.sessions));const unlocked=updateAchievements(s);run.newAchievements=unlocked;s[mode==='daily'?'activeSession':'practiceDraft']=null;setState(s);round=null;lastSummary=run;renderSummary(run);refreshHeader();tone(unlocked.length?'achievement':'finish');
}
function resultColor(a){return a.skipped?'#8995a8':a.error<=2?'#91d5aa':a.error<=5?'#f4d18b':a.error<=10?'#efbc87':'#f7a594'}
function resultRows(s){return s.answers.map(a=>{const unit=a.error===1?'año':'años',status=a.skipped?'Repasar':a.error===0?'Exacta':`${a.error} ${unit}`;return `<div class="result-row"><i class="swatch" style="--result:${resultColor(a)}"></i><div><b>${esc(a.title)}</b><small>${a.skipped?`Fecha revelada · ${a.actual}`:`Tu ${a.guess} · correcta ${a.actual}`}</small></div><strong>${status}</strong></div>`}).join('')}

function summaryNarrative(s,priorAvg){
  if(s.omitted>=2)return `Revelaste ${s.omitted} fechas; ya quedaron marcadas para reforzarlas.`;
  if(s.exact>=3)return `Acertaste ${s.exact} de ${s.answers.length} fechas de forma exacta.`;
  if(Number.isFinite(s.avg)&&s.avg<=3)return 'Tus estimaciones quedaron muy cerca de las fechas reales.';
  if(Number.isFinite(priorAvg)){const delta=priorAvg-s.avg;if(delta>=2)return `Reduciste tu error medio en ${fmt(delta)} años respecto de tus partidas anteriores.`;if(delta<=-2)return 'Hoy hubo más distancia que en tus partidas anteriores; el repaso puede fijar las fechas más difíciles.';}
  return 'Una partida más para afinar tu mapa del tiempo.';
}
function legacySummarySignatureV11(s){
  return `<div class="answer-signature" aria-label="Resumen visual de las ${s.answers.length} respuestas">${s.answers.map((a,i)=>{const unit=a.error===1?'año':'años',status=a.skipped?'Revelada':a.error===0?'Exacta':`${a.error} ${unit}`,route=a.skipped?`Fecha ${a.actual}`:`${a.guess} → ${a.actual}`;return `<button class="answer-signature-item" data-action="detail" data-id="${a.id}" style="--result:${resultColor(a)}" aria-label="${esc(a.title)}. ${status}. Abrir contexto"><span class="signature-index">${i+1}</span><span class="signature-copy"><b title="${esc(a.title)}">${esc(a.title)}</b><small>${route}</small></span><strong>${status}</strong></button>`}).join('')}</div>`;
}
function legacyRenderSummaryV11(s){
  if(!s)return;lastSummary=s;const state=getState(),isDaily=s.mode==='daily',errors=s.answers.filter(a=>a.skipped||a.error>5),unlocked=(s.newAchievements||[]).map(id=>ACHIEVEMENTS.find(a=>a.id===id)).filter(Boolean),prior=state.sessions.filter(x=>x.date!==s.date&&Number.isFinite(x.avg)),priorAvg=prior.length>=3?mean(prior.map(x=>x.avg)):null,activity=isDaily?`${recentActivity(state)} de 7 días · racha ${calcStreak(state.sessions)}`:'Sin impacto en tu racha diaria';
  const rewards=[s.newDiscoveries?`<span class="reward-line good"><b>${s.newDiscoveries}</b> nueva${s.newDiscoveries===1?' fecha':'s fechas'} en tu colección</span>`:'',unlocked.length?`<span class="reward-line accent"><b>${unlocked.length}</b> ${unlocked.length===1?'logro desbloqueado':'logros desbloqueados'} · ${unlocked.map(a=>esc(a.title)).join(' · ')}</span>`:''].filter(Boolean).join('');
  setView(`<section class="surface summary summary-v11"><header class="summary-head"><div><span class="eyebrow">${isDaily?`DESAFÍO #${s.challenge}`:s.mode==='review'?'REPASO':'PRÁCTICA'}</span><h1>${isDaily?'Tu resultado':'Sesión completada'}</h1></div><span class="summary-session-meta">${activity}</span></header><div class="summary-body"><section class="summary-result" aria-label="Resultado principal"><div class="summary-scoreline"><div class="summary-score"><b>${fmt(s.total,0)}</b><span>puntos</span></div><div class="summary-measures"><div><b>${fmt(s.avg)}</b><span>años de error</span></div><div><b>${s.exact}/${s.answers.length}</b><span>exactas</span></div></div></div><p class="summary-narrative">${summaryNarrative(s,priorAvg)}</p>${s.omitted?`<small>${s.omitted} fecha${s.omitted===1?'':'s'} revelada${s.omitted===1?'':'s'}; el promedio considera solo las respuestas estimadas.</small>`:''}${isDaily&&Number.isFinite(priorAvg)&&Number.isFinite(s.avg)?`<p class="summary-comparison">Promedio previo ${fmt(priorAvg)} años · hoy ${fmt(s.avg)}.</p>`:''}</section><section class="summary-round"><div class="summary-section-title"><span class="eyebrow">TU PARTIDA</span><span class="summary-section-hint">Toca un hito para abrir su contexto</span></div>${legacySummarySignatureV11(s)}</section>${rewards?`<section class="summary-rewards"><span class="eyebrow">LO QUE SUMASTE</span><div class="reward-lines">${rewards}</div></section>`:''}</div><footer class="summary-footer"><div class="summary-secondary-actions"><button class="secondary" data-view="coleccion">Colección</button><button class="secondary" data-action="share">Compartir</button></div>${errors.length?`<button class="primary summary-primary" data-action="review-results">Repasar estas ${errors.length} fechas →</button>`:`<button class="primary summary-primary" data-view="repaso">Seguir practicando →</button>`}</footer></section>`)
}

function startTimeline(){const reserved=reservedUpcomingIds(7),pool=QUESTIONS.filter(q=>!reserved.has(q.id));const qs=shuffled(pool,hashString(`${Date.now()}|${Math.random()}|order`)).slice(0,4);const s=getState();s.timelineDraft={ids:qs.map(q=>q.id),answered:false,results:[]};timelineSelection=null;setState(s);renderTimeline()}
function renderTimeline(){
  const s=getState();if(!s.timelineDraft){startTimeline();return}const t=s.timelineDraft;
  const cards=t.ids.map((id,i)=>{const q=displayQuestion(id),r=t.results.find(x=>x.id===id);return `<article class="order-card ${timelineSelection===id?'selected':''} ${t.answered?(r?.correct?'correct':'wrong'):''}" data-order-id="${id}" ${t.answered?'':'draggable="true"'}><div class="order-position"><span>${i+1}</span><span class="slot-label">${t.answered?'Posición final':'Lugar'}</span></div><div><button class="order-title" data-action="${t.answered?'detail':'select-order'}" data-id="${id}" ${t.answered?'':`aria-pressed="${timelineSelection===id}"`}>${esc(q.title)}</button><small class="order-subcategory">${esc(q.category)}</small></div>${t.answered?`<strong class="order-date">${q.year}</strong>`:`<div class="order-tools"><button data-action="move-order" data-id="${id}" data-step="-1" aria-label="Mover ${esc(q.title)} antes" ${i===0?'disabled':''}>←</button><button data-action="move-order" data-id="${id}" data-step="1" aria-label="Mover ${esc(q.title)} después" ${i===3?'disabled':''}>→</button></div>`}${t.answered?`<p class="order-explain" style="color:${r?.correct?'var(--good)':'var(--bad)'}">${r?.correct?'Estaba bien colocado':`Estaba en el lugar ${(r?.from??0)+1}`}</p>`:''}</article>`}).join('');
  setView(`<section class="surface timeline-layout"><header><div class="row between"><h1>Línea temporal</h1><button class="secondary" data-action="timeline-stats">Mi progreso</button></div><p class="muted">${t.answered?'Años revelados. Toca un hito para leer su historia.':timelineSelection?'Ahora toca la tarjeta del lugar al que quieres moverlo.':'Ordena de más antiguo a más reciente. Toca dos tarjetas o usa las flechas.'}</p></header><div class="order-list">${cards}</div><footer class="order-footer"><span>${t.answered?`${t.results.filter(r=>r.correct).length}/4 posiciones correctas · ${s.timeline.currentStreak} rondas perfectas seguidas`:'Los años se revelan al confirmar.'}</span><button class="primary" data-action="${t.answered?'new-order':'confirm-order'}">${t.answered?'Otra ronda →':'Confirmar orden'}</button></footer></section>`);
}
function moveTimeline(id,to){const s=getState(),t=s.timelineDraft;if(!t||t.answered)return;const from=t.ids.indexOf(id);if(from<0||to<0||to>=t.ids.length)return;const [q]=t.ids.splice(from,1);t.ids.splice(to,0,q);timelineSelection=null;setState(s);renderTimeline();tone('place')}
function selectTimeline(id){const t=getState().timelineDraft;if(!t||t.answered)return;if(timelineSelection===id)timelineSelection=null;else if(timelineSelection){moveTimeline(timelineSelection,t.ids.indexOf(id));return}else timelineSelection=id;renderTimeline()}
function confirmTimeline(){const s=getState(),t=s.timelineDraft;if(!t||t.answered)return;const original=[...t.ids],sorted=[...t.ids].sort((a,b)=>QUESTION_BY_ID.get(a).year-QUESTION_BY_ID.get(b).year),years=sorted.map(id=>QUESTION_BY_ID.get(id).year);t.results=original.map((id,from)=>({id,from,correct:QUESTION_BY_ID.get(id).year===years[from],displacement:Math.abs(QUESTION_BY_ID.get(id).year-years[from])}));t.ids=sorted;t.answered=true;timelineSelection=null;const correct=t.results.filter(x=>x.correct).length;s.timeline.rounds++;s.timeline.positions+=correct;s.timeline.elements+=4;s.timeline.perfect+=correct===4?1:0;s.timeline.currentStreak=correct===4?s.timeline.currentStreak+1:0;s.timeline.bestStreak=Math.max(s.timeline.bestStreak,s.timeline.currentStreak);for(const r of t.results){const q=QUESTION_BY_ID.get(r.id),d=decadeOf(q.year),v=s.timeline.decades[d]||{count:0,error:0,correct:0};v.count++;v.error+=r.displacement;v.correct+=r.correct?1:0;s.timeline.decades[d]=v;}const unlocked=updateAchievements(s);setState(s);renderTimeline();tone(correct===4?'exact':'confirm');if(unlocked.length)toast('Logro: '+unlocked.map(id=>ACHIEVEMENTS.find(a=>a.id===id).title).join(', '))}
function streakAtDate(date){const dates=new Set(getState().sessions.map(s=>s.date));let d=parseDateKey(date),n=0;while(dates.has(dateKey(d))){n++;d=addDays(d,-1)}return n}
function shareText(s){const mode=s.mode==='daily'?`#${s.challenge}`:s.mode==='review'?'REPASO':'PRÁCTICA';return `QUÉ AÑO ${mode}\n${s.answers.map(a=>a.skipped?'—':a.error===0?'✓':`+${a.error}`).join(' ')}\n${fmt(s.avg)} años · ${s.answers.length-s.omitted}/${s.answers.length} respondidas\n${s.total} pts${s.mode==='daily'?`\nRacha ${streakAtDate(s.date)}`:''}`}
function drawShareCard(canvas,s){const ctx=canvas.getContext('2d');if(!ctx)return;canvas.width=900;canvas.height=600;const p=getState().preferences.palette,accent={amber:'#f4c76d',ocean:'#7acff2',violet:'#c4b1ff'}[p]||'#f4c76d';ctx.fillStyle='#10151e';ctx.fillRect(0,0,900,600);ctx.fillStyle=accent;ctx.fillRect(40,40,820,5);ctx.fillStyle='#f3f4ee';ctx.textAlign='left';ctx.font='800 48px system-ui';ctx.fillText(`QUÉ AÑO ${s.mode==='daily'?'#'+s.challenge:s.mode==='review'?'REPASO':'PRÁCTICA'}`,50,120);const size=Math.min(108,(800-(s.answers.length-1)*12)/s.answers.length);s.answers.forEach((a,i)=>{const x=50+i*(size+12);ctx.fillStyle=resultColor(a);ctx.fillRect(x,173,size,90);ctx.fillStyle='#10151e';ctx.textAlign='center';ctx.font='700 25px system-ui';if(!a.skipped&&a.error===0){ctx.strokeStyle='#10151e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+size*.3,218);ctx.lineTo(x+size*.44,230);ctx.lineTo(x+size*.72,204);ctx.stroke()}else ctx.fillText(a.skipped?'—':'+'+a.error,x+size/2,228)});ctx.textAlign='left';ctx.fillStyle='#f3f4ee';ctx.font='800 58px system-ui';ctx.fillText(`${fmt(s.avg)} años`,50,365);ctx.font='600 32px system-ui';ctx.fillText(`${fmt(s.total,0)} pts`,50,420);ctx.fillStyle='#acb9ca';ctx.font='22px system-ui';ctx.fillText(`${s.answers.length-s.omitted}/${s.answers.length} respondidas${s.mode==='daily'?` · Racha ${streakAtDate(s.date)}`:' · Sin racha diaria'}`,50,475);ctx.fillStyle=accent;ctx.font='600 21px system-ui';ctx.fillText('Cinco hitos. Una historia que recordar.',50,545)}
async function copyShare(text){try{await navigator.clipboard.writeText(text);toast('Resultado copiado')}catch{openDialog('Copiar resultado',`<textarea readonly aria-label="Texto para compartir">${esc(text)}</textarea><p class="muted">Selecciona el texto y cópialo.</p>`);$('dialogContent').querySelector('textarea')?.select()}}
function downloadBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function downloadJSON(data,name){downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),name)}
function openShare(s=lastSummary){if(!s)return;lastSummary=s;openDialog('Tu resultado para compartir',`<canvas id="shareCanvas" style="width:100%;height:auto" aria-label="Tarjeta del resultado, sin preguntas"></canvas><div class="row"><button class="primary" data-action="download-share">Guardar imagen</button><button class="secondary" data-action="copy-share">Copiar texto</button>${navigator.share?'<button class="secondary" data-action="native-share">Compartir…</button>':''}</div>`);drawShareCard($('shareCanvas'),s)}