import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),store=new Map(),checks=[];
function boot(){
 const {document,window}=parseHTML(fs.readFileSync(root+'/index.html','utf8'));
 window.HTMLElement.prototype.focus=function(){};
 window.HTMLElement.prototype.showModal=function(){this.open=true};
 window.HTMLElement.prototype.close=function(){this.open=false};
 window.HTMLElement.prototype.getContext=function(){return new Proxy({},{get:()=>()=>{}})};
 window.matchMedia=q=>({matches:q.includes('pointer')});window.scrollTo=()=>{};
 const c=vm.createContext({console,document,window,location:{hash:''},navigator:{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},requestAnimationFrame:fn=>fn(),setTimeout:()=>0,clearTimeout,Date,Map,Set,Math,JSON,Intl,Blob,URL});
 // Engine-only harness: production renderer ownership lives in Atlas and is protected by Playwright.
 // These aliases keep the lightweight VM focused on state/persistence without reintroducing runtime writers.
 for(const name of ['content','scheduler','calendar','editorial','storage','game'])vm.runInContext(fs.readFileSync(root+'/js/'+name+'.js','utf8'),c,{filename:name+'.js'});
 vm.runInContext('renderGame=legacyRenderGameV11;renderSummary=legacyRenderSummaryV11;',c,{filename:'engine-test-render-adapter.js'});
 for(const name of ['panels','app'])vm.runInContext(fs.readFileSync(root+'/js/'+name+'.js','utf8'),c,{filename:name+'.js'});
 return {c,document,run:code=>vm.runInContext(code,c,{timeout:30000})};
}
let b=boot();const run=code=>b.run(code),check=(code,label)=>{assert.ok(run(code),label);checks.push(label)};
check("!$('view').textContent.includes('No pudimos')",'Initial rendering');
run('closeDialog();startDaily();setYear(1960);commitAnswer()');
check("round.phase==='answer'&&!$('yearInput')&&!!$('primaryAction')",'Answer replaces controls');
check('getState().activeSession.answers.length===1','Daily answer saved');
const first=run('round.questionIds[0]');
b=boot();run('closeDialog()');check("round.phase==='answer'&&round.answers.length===1",'Reload resumes answer screen');
run('nextQuestion();showView("repaso");startPractice("all","Todas",3)');
check('round.questionIds.length===3','Practice size');
run('commitAnswer(true);nextQuestion();setYear(2000);commitAnswer();nextQuestion();setYear(2000);commitAnswer();nextQuestion()');
check('getState().sessions.length===0&&getState().practiceSessions.length===1','Practice history separate');
check('getState().practiceSessions[0].answers[0].error===null&&getState().practiceSessions[0].omitted===1','Skip has no fabricated error');
check('getState().activeSession.answers.length===1','Practice preserves daily draft');
run('showView("hoy")');check('round.index===1','Daily resumes correct index');
run('while(round){setYear(1990);commitAnswer();nextQuestion()}');
check('getState().sessions.length===1&&getState().activeSession===null','Daily completes once');
run('showView("hoy");completeRound()');check('getState().sessions.length===1','Duplicate completion guarded');
check(`getState().questionStats[${JSON.stringify(first)}].attempts===1`,'Reload does not double count memory');
run('showView("orden")');check("!$('view').querySelector('.order-date')",'Ordering hides years');
run('getState().timelineDraft.ids.sort((a,b)=>QUESTION_BY_ID.get(a).year-QUESTION_BY_ID.get(b).year);confirmTimeline();confirmTimeline()');
check('getState().timeline.rounds===1&&getState().timeline.positions===4&&getState().timeline.perfect===1','Ordering positions and duplicate confirmation');
check('getState().sessions.length===1','Ordering preserves daily history');
for(const v of ['repaso','coleccion','estadisticas','hoy']){b.document.querySelector(`[data-view="${v}"]`).click();check(`currentView==='${v}'`,'Navigation event: '+v)}
for(const m of ['cards','decade','category','map','achievements'])run(`collectionState.mode='${m}';renderCollection()`);
for(const t of ['summary','trend','detail','calendar'])run(`statsState.tab='${t}';renderStats()`);
run('openTimelineStats();closeDialog();openSettings();closeDialog();openEditor();closeDialog();openShare(getState().sessions[0]);closeDialog()');checks.push('All section renderers, dialogs and share canvas commands');
check('practiceQuestions("Cine","unseen",10).every(q=>q.category==="Cine"&&!discoveredIds().has(q.id))','Practice filters respected');
check('practiceQuestions("Todas","all",10).every(q=>!reservedUpcomingIds(7).has(q.id))','Upcoming daily questions reserved');
check('auditQuestionBank().total===300&&auditQuestionBank().images===45','Bank and asset counts');
run('const ms=defaultState();const aa=()=>({id:"jfk",error:0,guess:1963,actual:1963,points:1000,skipped:false,assisted:false});recordAnswer(ms,aa(),"2026-01-01");recordAnswer(ms,aa(),"2026-01-01");recordAnswer(ms,aa(),"2026-01-02")');
check('mastery(ms.questionStats.jfk).key!=="mastered"','Repeated same-day answers do not consolidate');
run('recordAnswer(ms,aa(),"2026-01-08")');check('mastery(ms.questionStats.jfk).key==="mastered"','Spaced successes consolidate');
run('const legacy=defaultState();legacy.sessions=[sessionFromAnswers("2026-01-01",QUESTIONS.slice(0,5).map(q=>({id:q.id,guess:q.year+2,actual:q.year,error:2,points:points(2)})))];const migrated=migrateState(legacy)');
check('Object.values(migrated.questionStats).every(s=>s.attempts===1&&s.avgError===2)','Legacy history reconstructs missing memory');
run('const recovered=migrateState(JSON.parse(JSON.stringify(getState())))');
check('recovered.sessions.length===1&&recovered.practiceSessions.length===1&&recovered.timeline.rounds===1','Backup roundtrip preserves histories');
const simulation=run('simulateSchedule(365)');assert.ok(simulation.allSpecialsValid&&simulation.minGap>=30);checks.push('365-day cooldown and special integrity');
fs.writeFileSync(path.join(root,'test-results.json'),JSON.stringify({method:'Node VM + LinkeDOM simulated DOM; no browser layout or audio playback testing',checks,schedule:{minGap:simulation.minGap,specials:simulation.specials.length}},null,2));
console.log(JSON.stringify({passed:checks.length,checks,minGap:simulation.minGap},null,2));